AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/Gemfile'
    - 'bin/**/**'
    - 'config/**/**'
    - 'db/**/**'
    - 'spec/**/**'
    - 'test/**/*'
    - 'test/*'
    - 'temp/**/**'
    - 'vendor/**/**'

LineLength:
  Max: 100

MethodLength:
  CountComments: false
  Max: 30
Metrics/AbcSize:
  Enabled: true
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Blocks:
  Enabled: false
