AllCops:
  Exclude:
    - '**/Gemfile'
    - 'bin/**/**'
    - 'config/**/**'
    - 'db/**/**'
    - 'spec/**/**'
    - 'test/**/*'
    - 'test/*'
    - 'temp/**/**'
    - 'vendor/**/**'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
